services:
  ai-api:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    ports: 
      - "5166:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - data_protection_keys:/root/.aspnet/DataProtection-Keys
    networks:
      - sats

  postgres:
    image: postgres:17.4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sats

volumes:
  data_protection_keys:
    driver: local
  postgres_data:
    driver: local

networks:
  sats:
    driver: bridge