@Host = http://localhost:5166/api

GET {{Host}}/test
Accept: application/json

###

POST {{Host}}/chat/5EFEA1C9-97D0-4052-8BEA-C9B5E84EB5D9
Accept: text/plain
Content-Type: application/json

"What is OpenAI?"
